---
- name: Install Firefox on Windows
  hosts: all
  gather_facts: false

  tasks:

    - name: Download Firefox installer
      ansible.windows.win_get_url:
        url: 'https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=en-US'
        dest: 'C:\Windows\Temp\FirefoxSetup.exe'

    - name: Install Firefox
      ansible.windows.win_package:
        path: 'C:\Windows\Temp\FirefoxSetup.exe'
        arguments: '/S'
        state: present

    - name: Remove Firefox installer
      ansible.windows.win_file:
        path: 'C:\Windows\Temp\FirefoxSetup.exe'
        state: absent